package DBAuthTest::Model::test_auth;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'test_auth::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:test_auth',
        user => 'root',
        password => '1',
    }
);

=head1 NAME

DBAuthTest::Model::test_auth - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<DBAuthTest>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<test_auth::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Dragos

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
